import { Montserrat } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const inter = Montserrat({ subsets: ["latin"] });
import { social_Icons } from "@/constants/data";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        <div className="socialIcons flex flex-col gap-4 fixed top-[50%] right-[20px] translate-y-[-50%]">
          {social_Icons.map((item, i) => (
            <Link href={item.path} key={i} className="text-[32px] text-green cursor-pointer">
              {item.icon}
            </Link>
          ))}
        </div>
      </body>
    </html>
  );
}
